PR_add_project
maksim-politech/Diplom2_API pull request #1
Opened 2023-01-08 21:38 UTC by maksim-politech

2023-01-16 21:28 UTC, pavel-ulan requested changes
Есть, что поправить, есть о чем почитать. Много хардкода тестовых данных в тестах. По хорошему это все стоило бы вынести, но это на твое усмотрение.

2023-01-16 21:28 UTC, pavel-ulan commented on src/test/java/CreateUserTest.java
> +        }
*надо исправить*
Я еще понимаю, когда UI глючит и на этом фоне когда не работают нормальные ожидания, приходится прибегать к sleep (хотя даже в этом случае, это неприемлемо и надо искать пути решения этой проблемы другими путями).
При работе с API использование sleep неприемлемо ни при каких условиях. Есть много способов обойтись чем-то другим. И довольно многое можно решить просто правильной конфигурацией Rest-Assured. Так например он позволяет отправлять повторный запрос при превышении времени ожидания. или делать несколько запросов если сервер не отвечает.
В любом случае использование sleep в тестах, это запрещенный прием.
Это было лирическое отступление про sleep, когда он используется в тестах. У тебя же он просто зачем-то есть (причем он совершенно ничего не делает). Я надеюсь, что ты его при дебаге использовал для каких-то целей и просто забыл удалить.

2023-01-17 16:42 UTC, maksim-politech commented on src/test/java/CreateUserTest.java
> +        }
Я использовал, посоветовавшись с одногруппниками, как решением проблемы с множественными реквестами при составления отчета алюровского (ошибка 429 кажется , слишком много запросов)

2023-01-21 21:11 UTC, pavel-ulan commented on src/test/java/CreateUserTest.java
> +        }
Да, видел, что такие глюки бывают. Я вижу 2 решения как минимум: - запустить тесты со слипом, запушить результаты аллюра, удалить слип, запушить тестовые классы. (не очень красиво, но ок. текущая ситуация требует такого решения. в любом случае, на реальном проекте так сделать не получится).
- залить те результаты которые есть, написать, что такие-то тесты падают, т.к. срабатывает защита сервера от DDOS.

и даже 3 решение есть. разобраться почему возникает эта ошибка и понять как ее обойти. я не разбирался со стендом (у меня нет доступа к нему), но могу предположить, что это защита от DDOS атак и в какой-то момент она начинает отсекать часть запросов. у такого режима есть время отката (условно сутки) и можно попробовать просто запустить тесты на следующий день. т.е. ты вечером доделываешь тесты, часто гоняешь, что бы проверить результаты, начинаешь получать периодами 429, не обращаешь внимания и доделываешь работу. проверяешь, что по отдельности тесты работают. на следующий день просто запускаешь их. в теории должно все пройти хорошо (если проблема в этом. я могу ошибаться). в любом случае, можно попробовать разобраться, но это несомненно потребует больше времени.

2023-01-21 21:14 UTC, pavel-ulan approved these changes
Ок, тут еще есть, что исправить, но это уже некритичные моменты и работу можно принять

2023-01-21 21:14 UTC, pavel-ulan commented on src/test/java/UpdateUserTest.java
> +        System.out.println(response.body().asString());
*можно лучше*
не используй в финальной версии sout. для таких целей существуют логгеры.

2023-01-22 10:12 UTC, maksim-politech commented on src/test/java/UpdateUserTest.java
> +        System.out.println(response.body().asString());
Пропустил по всей видимости в этой части задания, но исправил данное замечание в другой.

2023-01-22 10:18 UTC, maksim-politech commented on src/test/java/UpdateUserTest.java
> +        System.out.println(response.body().asString());
Поправил

2023-01-22 20:56 UTC, pavel-ulan approved these changes

2023-01-22 20:56 UTC, pavel-ulan commented on src/test/java/UpdateUserTest.java
> +                .statusCode(200); ///дОЛЖЕН БЫТЬ 403 СТАТУС КОД ПО ДОКУМЕНТАЦИИ, НО ВЫДАЕТ 200
так почему ты проверяешь 200? если по докам 403, то и проверяй 403. 200 это баг =)

2023-01-23 18:54 UTC, maksim-politech commented on src/test/java/UpdateUserTest.java
> +                .statusCode(200); ///дОЛЖЕН БЫТЬ 403 СТАТУС КОД ПО ДОКУМЕНТАЦИИ, НО ВЫДАЕТ 200
@pavel-ulan У вас (у яндекса) написано, что тесты все должны быть успешными при сдаче

2023-09-27 18:40 UTC, merged